// +++++++++++++++++++++++++++++++++++++++++++++++<< CHAPTER 43 - 48 >> ++++++++++++++++++++++++++++++++++++++++++++

//                 <<<<<<<<<<<<<<<<<<<<<<<<<< task 1>>>>>>>>>>>>>>>>>>>>>>>

// function alertbox(){
//     alert ("this is alert box ")
// }

//  <<<<<<<<<<<<<<,,,task 2>>>>>>>>>>>>>>>>>>

// function imgalert(){
//     alert("thanks for purchasing a phone from us")
// }

//   <<<<<<<<<<<<<<< task 3 >>>>>>>>>>>>>>>>

// function deletebtn(){
    //   var td = event.target.parentNode; 
    //   var tr = td.parentNode; // the row to be removed
    //   tr.parentNode.removeChild(tr);
// }

//   <<<<<<<<<<<<<<< task 4 >>>>>>>>>>>>>>>>

// function changeimg(id,src){
//     var image = document.getElementById(id);
//         image.src = src
// }

// <<<<<<<<<<<<<<<<<<<< task 5 >>>>>>>>>>>>>>>>>>>

// var counter = 0;
//     function increse() {
//         counter += 1;
//         document.getElementById("display").innerHTML = counter;
//     }
//     function decreses() {
//         counter -= 1;
//         document.getElementById("display").innerHTML = counter;
//     }
