// //Task 1
// var teacher, student, principal;


// //Task 2
// //legal
// var $myworld, string_html, key1, king$, userinput;
// //illegal
// var 1stride, comman - word;, @myworld, Code.1, zebra & lion;

// document.write("<h2> Rules for naming JS variable </h2>");
// document.write("Variable names can only contain letters, numbers, dollarSign and underScore. Forexampel $my_1stVariable");
// document.write("<br>Variable names must begin with a letter, $, _. Forexampel $name, _name or name");
// document.write("<br>Variable names are Case Sensitive");
// document.write("<br>Variable name should not be JS keyword");