// //Task 1
// var userName;

// //Task 2
// var myName = "Muhammad Hazique Khatri";

// //Task 3
// var message = "Hello World";
// // window.alert(message);

// //Task 4    ==> (Student Bio Data..)
// var name = "Muhammad Hazique Khatri";
// var age = 19;
// var about = "Certified Mobile Application Development";
// // window.alert(name);
// // window.alert(age + " Years Old");
// // window.alert(about);

// //Task 5
// var string = "PIZZA";
// var s;
// function loop(input) {
//     s = "";
//     var arr = ["P", "I", "Z", "Z", "A"];
//     for (var i = 0; i < input; i++) {
//         s += arr[i];
//     }
//     return s;
// }
// // window.alert(loop(5) + "\n" + loop(4) + "\n" + loop(3) + "\n" + loop(2) + "\n" + loop(1));


// //Task 6
// var email = "example@example.com"
// // window.alert("My email address is " + email);

// //Task 7
// var book = "A smarter way to learn JavaScript";
// // window.alert("Iam trying to learn from the book " + book);

// //Task 8
// var mssg = "Yah! I can write HTML content through JavaScript";
// // document.write(mssg);

// //Task 9
// window.alert("▬▬▬▬▬▬▬▬▬ஜ۩۞۩ஜ▬▬▬▬▬▬▬▬▬");