//                                             CHAPTER  01
// TASK 01


// window.alert("Welcome to the Website!")


// TASK 02


// window.alert("Error! Please Enter a valid Password.")

// TASK 03

// window.alert("Welcome To JS Land... \nHappy Coding!");

// TASK 04

// window.alert("Welcome to JS Land...");
// window.alert("Happy Coding!");


// TASK 05


// window.alert("Hello... I can run JS through my web browser's console.");


// TASK 06

// window.alert("Hello World!");

// TASK 07


// window.alert("Hello World!");


